spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  webflux:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5999/university
    username: postgres
    password: 921
