DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS teacher_courses;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS lesson_time;
DROP TABLE IF EXISTS lesson_rooms;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS groups;




